# string
version: 0.0.1

# int
test_int: 1

data_repository:
    data_source: ../repository/data_source
    landing: ../repository/landing
    staging: ../repository/staging
    feature_store: ../repository/feature_store
    prediction: ../prediction
    artifact: ../artifact
    metadata: ../repository/metadata
    
features:
    entity: [house_id]
    target: [MEDV]
    event_timestamp: [event_timestamp]
    load_date: [load_dt]
    proportion: [ZN, INDUS, RM, PTRATIO, B, LSTAT]
    geography: [CHAS,DIS, RAD]
    toxic: [NOX]
    monetary: [TAX]

feature_groups: [target, proportion, geography, toxic, monetary]
    
script:
    project_init: ../script/project_init.py
    generate_doc: ../script/generate_doc.py
    clean: ../script/clean.py
    aggregate: ../script/aggregate.py
    join: ../script/join.py
    feature_engineering: ../script/feature_engineering.py
    scope_and_split: ../script/scope_and_split.py
    train: ../script/train.py
    benchmark: ../script/benchmark.py
    explainability: ../script/explainability.py
    online_serving: ../script/online_serving.py
    offline_serving: ../script/offline_serving.py
    drift_detection: ../script/drift_detection.py

    