# string
version: 0.0.1

# int
test_int: 1

data_repository:
    repository: ../repository
    data_source: ../repository/data_source
    landing: ../repository/landing
    staging: ../repository/staging
    feature_store: ../repository/feature_store
    prediction: ../prediction
    artifact: ../artifact
    metadata: ../repository/metadata
    reference: ../repository/metadata/reference
    database: ../repository/metadata/database
    experiment: ../repository/metadata/experiment

feature_store_config:
    fs_repo_config: ../config
    feast_fs_yaml: ../config/feature_store.yaml
    ttl: 1
    materialize_day: 700

# features:
#     entity: [house_id]
#     target: [MEDV]
#     timestamp_field: [event_timestamp]
#     event_timestamp: [event_timestamp]
#     load_date: [load_dt]
#     proportion: [ZN, INDUS, RM, PTRATIO, B, LSTAT]
#     geography: [CHAS,DIS, RAD]
#     toxic: [NOX]
#     monetary: [TAX]

feature_groups: [target, proportion, geography, toxic, monetary]
    
script:
    project_init: ../script/project_init.py
    generate_doc: ../script/generate_doc.py
    clean: ../script/clean.py
    aggregate: ../script/aggregate.py
    join: ../script/join.py
    feature_engineering: ../script/feature_engineering.py
    fv_register: ../script/fv_register.py
    create_reference: ../script/create_reference.py
    materialize: ../script/materialize.py
    scope_and_split: ../script/scope_and_split.py
    train: ../script/train.py
    benchmark: ../script/benchmark.py
    explainability: ../script/explainability.py
    online_serving: ../script/online_serving.py
    offline_serving: ../script/offline_serving.py
    drift_detection: ../script/drift_detection.py
    
model_tracking:
    tracking_uri: "http://localhost:5000"
    mlrun_path: "/usr/src/datanoob/repository/metadata/mlruns"
    
eda:
    host: localhost
    port: 555

    